
logs:
  show_access_logs: true
  access_logs_fields:
  - ${REQUEST:method}
  - ${REQUEST:host}
  - ${REQUEST:path}
  - ${REQUEST:proto}
  - ${REQUEST:referer}

  - ${REQUEST_HEADER:user-agent}
  - ${REQUEST_HEADER:x-forwarded-for}
  - ${REQUEST_HEADER:x-real-ip}

  - ${RESPONSE_HEADER:content-length}
  - ${RESPONSE_HEADER:content-type}
  

proxies:
  - name: varnish

    listener:
      port: 8080
      address: 0.0.0.0

    backends:
      # static:
      #   - name: varnish-01
      #     host: 127.0.0.1:8081

      #   - name: varnish-02
      #     host: 127.0.0.1:8082

      #   - name: varnish-03
      #     host: 127.0.0.1:8083

      dns:
        name: varnish-service
        domain: example.com
        port: 80
        synchronization: 10s

    hash_key:

      # Key to generate a hash from the request. It can be composed using any of the following:
      # ${REQUEST:scheme}, ${REQUEST:host}, ${REQUEST:port}, ${REQUEST:path}, ${REQUEST:query}
      # ${REQUEST:method}, ${REQUEST:proto}
      pattern: "${REQUEST:path}"

    # Aditional options such as hashing mode or TTL
    options:
      protocol: http # http or http2
      # certificate: /etc/ssl/certs/achetronic.pem
      # key: /etc/ssl/private/achetronic.key
