{{ if .Values.agent.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hashrouter.fullname" . }}-agent-config
  labels:
    {{- include "hashrouter.labels" . | nindent 4 }}
  {{- with .Values.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

data:
  hashrouter.yaml: |-
    {{- .Values.agent.config | nindent 4 }}
{{- end }}