apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hashrouter.fullname" . }}
  labels:
    {{- include "hashrouter.labels" . | nindent 4 }}
  {{- with .Values.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "hashrouter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hashrouter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hashrouter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          command:
            - /hashrouter
            - run
            - --config
            - /etc/agent/hashrouter.yaml

          {{- with .Values.agent.extraArgs }}
          args:
            {{ toYaml . | nindent 10 }}
          {{- end }}

          {{- with .Values.agent.env }}
          env:
            {{ toYaml . | nindent 10 }}
          {{- end }}

          {{- with .Values.agent.envFrom }}
          envFrom:
            {{ toYaml . | nindent 10 }}
          {{- end }}

          # TODO: Good first issue
          {{- with .Values.agent.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.agent.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}

          volumeMounts:
            - name: agent-config
              mountPath: /etc/agent/
            {{- with .Values.agent.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: agent-config
          configMap:
            name: {{ include "hashrouter.fullname" . }}-agent-config
        {{- with .Values.agent.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}


